conda:
   file: docs/environment.yml

build:
   image: latest

python:
   version: 3.8
   install:
      - method: setuptools
        path: seaflux

submodules:
   include: all

sphinx:
  fail_on_warning: true
